# Generated by Django 6.1.1 on 2026-10-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(default='B1', max_length=255)),
                ('age_bucket', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults')], default=None, max_length=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=80)),
                ('teacher_context', models.TextField(blank=True, null=True)),
                ('extra_instructions', models.TextField(blank=True, null=True)),
                ('textbook_hint', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('draft', 'Draft'), ('approved', 'Approved'), ('error', 'Error')], default='generated', max_length=10)),
                ('final', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('structured_content', models.JSONField(blank=True, null=True)),
                ('level', models.CharField(default='B1', max_length=255)),
                ('age_bucket', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults')], default=None, max_length=10, null=True)),
                ('teacher_context', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.JSONField(blank=True, null=True)),
                ('iteration_number', models.PositiveIntegerField(default=1)),
                ('generated_lesson', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.generatedlesson')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reference', 'Reference'), ('material', 'Material'), ('final', 'Final')], default='reference', max_length=10)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='attachments/')),
                ('generated_lesson', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.generatedlesson')),
                ('reference_lesson', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.referencelesson')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('lesson_iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessoniteration')),
            ],
        ),
    ]
