# Generated by Django 6.1.1 on 2026-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedlesson',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('draft', 'Draft'), ('approved', 'Approved'), ('error', 'Error')], default='draft', max_length=10),
        ),
    ]
