# Generated by Django 6.1.1 on 2026-10-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lessoniteration_generated_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoniteration',
            name='generated_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='api.generatedlesson'),
        ),
    ]
