# Generated by Django 6.1.1 on 2026-10-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lessoniteration_generated_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedlesson',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
