# Generated by Django 6.1.1 on 2026-10-04 08:14

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_generatedlesson_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.referencelesson')),
            ],
        ),
    ]
