# Generated by Django 6.1.1 on 2026-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lessonchunk'),
        ('api', '0007_auto_20261004_0819'),
    ]

    operations = [
    ]
