# Generated by Django 6.1.1 on 2026-10-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0006_lessonchunk_0007_auto_20261004_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='generated_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.generatedlesson'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='reference_lesson',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.referencelesson'),
        ),
    ]
