# Generated by Django 6.1.1 on 2026-10-04 09:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_attachment_generated_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
