# Generated by Django 6.1.1 on 2026-10-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_lessonchunk_embedding_384'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonchunk',
            name='generated',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.generatedlesson'),
        ),
        migrations.AlterField(
            model_name='lessonchunk',
            name='reference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.referencelesson'),
        ),
    ]
