# Generated by Django 6.1.1 on 2026-10-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lessonchunk_generated_alter_lessonchunk_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherremark',
            name='lesson_iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='api.lessoniteration'),
        ),
    ]
